/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

export interface ActiveTasksCard {
  active_count: number;
  completed_this_week: number;
}
