/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

export interface BestFitInput {
  task_title: string;
  task_description?: string;
  /**
   * @maximum 100
   * @exclusiveMinimum 0
   */
  max_results?: number;
}
