/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

export interface ConnectedIntegrationsCard {
  jira_connected: boolean;
  github_connected: boolean;
  jira_token_expires_at: string | null;
  jira_token_expiring_soon: boolean;
  jira_site_url: string | null;
  github_org_name: string | null;
  health_status: string;
  health_message: string;
}
