/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */
import type { ActiveTasksCard } from './activeTasksCard';
import type { PendingAssignmentsCard } from './pendingAssignmentsCard';
import type { ResourceUtilizationStatus } from './resourceUtilizationStatus';
import type { TeamAllocation } from './teamAllocation';
import type { TeamMembersCard } from './teamMembersCard';
import type { TeamUtilizationCard } from './teamUtilizationCard';

export interface DashboardResponse {
  team_members: TeamMembersCard;
  team_utilization: TeamUtilizationCard;
  active_tasks: ActiveTasksCard;
  pending_assignments: PendingAssignmentsCard;
  resource_allocation_by_team: TeamAllocation[];
  resource_utilization: ResourceUtilizationStatus;
}
