/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */
import type { TeamMembersCard } from './teamMembersCard';

export interface DashboardResponse {
  team_members: TeamMembersCard;
}
