/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for developer workload calculation.
 */
export interface DeveloperWorkload {
  jira_account_id: string;
  display_name: string | null;
  email: string | null;
  /** Issues with status 'Open' or 'To Do' */
  open_issues?: number;
  /** Issues with status 'In Progress' */
  in_progress_issues?: number;
  /** Issues with status 'In Review' */
  in_review_issues?: number;
  /** Total active issues */
  total_active_issues?: number;
  /** High/Highest priority issues */
  high_priority_count?: number;
  /** Medium priority issues */
  medium_priority_count?: number;
  /** Low/Lowest priority issues */
  low_priority_count?: number;
  bugs_count?: number;
  tasks_count?: number;
  stories_count?: number;
  other_count?: number;
  /** Weighted workload score based on priority and issue type */
  workload_score?: number;
  last_updated?: string | null;
}
