/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

export interface GitHubUser {
  login: string;
  id: number;
  email?: string | null;
  name?: string | null;
  avatar_url?: string | null;
  html_url?: string | null;
}
