/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request to connect GitHub account to profile.
 */
export interface GitHubConnectionRequest {
  github_id?: number | null;
  github_login: string;
  github_display_name?: string | null;
  github_email?: string | null;
  github_avatar_url?: string | null;
}
