/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */
import type { ContributorPRCount } from './contributorPRCount';
import type { RepoPRCount } from './repoPRCount';

export interface GitHubPRStatsCard {
  total_active_prs: number;
  prs_by_repo: RepoPRCount[];
  top_contributors: ContributorPRCount[];
}
