/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */
import type { PullRequestContent } from './pullRequestContent';

export type GithubGetClosedPrsContextAllAuthors200 = {[key: string]: PullRequestContent[]};
