/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response after completing OAuth callback.
 */
export interface JiraAuthCallbackResponse {
  status: string;
  cloud_id?: string | null;
  jira_site_url?: string | null;
  expires_at?: string | null;
  scope?: string | null;
}
