/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for Jira user information.
 */
export interface JiraUser {
  /** Jira account ID */
  account_id: string;
  /** User display name */
  display_name?: string | null;
  /** User email address */
  email_address?: string | null;
  /** User avatar URL */
  avatar_url?: string | null;
  /** Whether user is active */
  active?: boolean;
}
