/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request schema for manual Jira sync.
 */
export interface JiraSyncRequest {
  /** Specific projects to sync. If None, syncs all. */
  project_keys?: string[] | null;
  /**
   * Maximum issues to fetch per project
   * @minimum 1
   * @maximum 1000
   */
  max_results?: number;
  /** Include closed/done issues */
  include_closed?: boolean;
  /** Include issue comments */
  sync_comments?: boolean;
  /** Generate embeddings for NLP */
  generate_embeddings?: boolean;
}
