/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

export type JiraGetIssueVectorsParams = {
/**
 * Filter by project key
 */
project_key?: string | null;
/**
 * Filter by assignee
 */
assignee_account_id?: string | null;
/**
 * @minimum 1
 * @maximum 500
 */
limit?: number;
};
