/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response schema for Jira sync operation.
 */
export interface JiraSyncResponse {
  status: string;
  projects_synced: string[];
  issues_synced: number;
  issues_updated: number;
  issues_created: number;
  embeddings_generated: number;
  errors?: string[];
  sync_duration_seconds: number;
}
