/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */
import type { JiraComment } from './jiraComment';
import type { JiraUser } from './jiraUser';

/**
 * Schema for Jira issue content with context for embeddings.
 */
export interface JiraIssueContent {
  issue_id: string;
  issue_key: string;
  project_key: string;
  summary: string;
  description?: string | null;
  issue_type: string;
  status: string;
  priority?: string | null;
  labels?: string[];
  assignee?: JiraUser | null;
  reporter?: JiraUser | null;
  /**
   * @minLength 1
   * @maxLength 2083
   */
  issue_url: string;
  comments?: JiraComment[];
  created_at?: string | null;
  updated_at?: string | null;
  resolved_at?: string | null;
  context?: string | null;
}
