/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

export type JiraGetAllJiraUsersParams = {
/**
 * @minimum 1
 * @maximum 1000
 */
max_results?: number;
};
