/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

/**
 * Lightweight schema for a single open Jira issue.
 */
export interface JiraOpenIssue {
  /** Internal Jira issue ID (numeric string) */
  issue_id: string;
  /** Human-readable issue key, e.g. PROJ-42 */
  issue_key: string;
  /** Issue summary / title */
  title: string;
  /** Issue description text */
  description?: string | null;
  /** Current issue status */
  status: string;
  /** Issue priority level */
  priority?: string | null;
}
