/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response for initiating Atlassian OAuth connect.
 */
export interface JiraAuthConnectResponse {
  /**
   * @minLength 1
   * @maxLength 2083
   */
  auth_url: string;
  state: string;
}
