/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

export type JiraGetOpenIssuesParams = {
/**
 * Filter by Jira project key (e.g. PROJ)
 */
project_key?: string | null;
/**
 * Maximum number of issues to return
 * @minimum 1
 * @maximum 500
 */
max_results?: number;
};
