/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */
import type { JiraUser } from './jiraUser';

/**
 * Schema for Jira issue comments.
 */
export interface JiraComment {
  id: string;
  author: JiraUser;
  body: string;
  created: string;
  updated?: string | null;
}
