/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request to connect Jira account to profile.
 */
export interface JiraConnectionRequest {
  jira_account_id: string;
  jira_display_name?: string | null;
  jira_email?: string | null;
  jira_avatar_url?: string | null;
}
