/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

export type JiraSearchSimilarIssuesParams = {
query: string;
/**
 * @minimum 1
 * @maximum 50
 */
n_results?: number;
project_key?: string | null;
assignee_account_id?: string | null;
};
