/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

/**
 * Generic message schema.
 */
export interface Message {
  message: string;
}
