/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

/**
 * New password reset schema.
 */
export interface NewPassword {
  token: string;
  /**
   * @minLength 8
   * @maxLength 128
   */
  new_password: string;
}
