/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

export type ProfilesListProfilesParams = {
/**
 * Filter by Jira connected
 */
has_jira?: boolean | null;
/**
 * Filter by GitHub connected
 */
has_github?: boolean | null;
/**
 * @minimum 1
 * @maximum 500
 */
limit?: number;
};
