/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */
import type { ProfileWorkloadCardJiraVsGithubSplit } from './profileWorkloadCardJiraVsGithubSplit';
import type { UserWorkload } from './userWorkload';

export interface ProfileWorkloadCard {
  jira_vs_github_split: ProfileWorkloadCardJiraVsGithubSplit;
  overloaded_members: UserWorkload[];
  idle_members: UserWorkload[];
}
