/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

export interface ProfileIntegrationsCard {
  jira_connected: number;
  jira_unconnected: number;
  github_connected: number;
  github_unconnected: number;
}
