/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

/**
 * Workload metrics for a profile.
 */
export interface ProfileWorkload {
  user_id: string;
  display_name?: string | null;
  jira_workload?: number;
  github_workload?: number;
  total_workload?: number;
  last_updated?: string | null;
}
