/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */
import type { GitHubUser } from './gitHubUser';
import type { JiraUser } from './jiraUser';

/**
 * Response schema for a matched Jira/GitHub profile pair.
 */
export interface ProfileMatchResponse {
  github_account: GitHubUser;
  jira_account?: JiraUser | null;
  match_score: number;
}
