/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

export type ProfilesMatchJiraGithubProfilesParams = {
/**
 * Matching threshold (0-100)
 * @minimum 0
 * @maximum 100
 */
threshold?: number;
};
