/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */
import type { DomainCount } from './domainCount';
import type { SkillCount } from './skillCount';

export interface ProfileSkillsCard {
  top_skills: SkillCount[];
  top_domains: DomainCount[];
}
