/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

export interface PrScoreInfo {
  pr_id: number;
  pr_title?: string;
  pr_description?: string;
  pr_url?: string;
  match_percentage?: number;
}
