/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */
import type { GitHubUser } from './gitHubUser';

export interface PullRequestContent {
  id: number;
  number: number;
  title: string;
  body?: string | null;
  context?: string | null;
  /**
   * @minLength 1
   * @maxLength 2083
   */
  html_url: string;
  /** The author of the pull request */
  author: GitHubUser;
}
