/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for creating a resource profile.
 */
export interface ResourceProfileCreate {
  skills?: string | null;
  domains?: string | null;
  user_id: string;
}
