/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response schema for resource profile.
 */
export interface ResourceProfileResponse {
  id: number;
  user_id: string;
  jira_account_id?: string | null;
  jira_display_name?: string | null;
  jira_email?: string | null;
  jira_avatar_url?: string | null;
  jira_connected_at?: string | null;
  has_jira?: boolean;
  github_id?: number | null;
  github_login?: string | null;
  github_display_name?: string | null;
  github_email?: string | null;
  github_avatar_url?: string | null;
  github_connected_at?: string | null;
  has_github?: boolean;
  skills?: string[];
  domains?: string[];
  jira_workload?: number;
  github_workload?: number;
  total_workload?: number;
  workload_updated_at?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
}
