/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

/**
 * User roles for RBAC.
 */
export type Role = typeof Role[keyof typeof Role];


export const Role = {
  admin: 'admin',
  moderator: 'moderator',
  user: 'user',
  guest: 'guest',
} as const;
