/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

export type ScoreGetBestFitsParams = {
/**
 * Task description to find best fits for
 */
task: string;
/**
 * Number of top developers to return
 * @maximum 100
 * @exclusiveMinimum 0
 */
top_n?: number;
};
