/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */
import type { PrScoreInfo } from './prScoreInfo';

export interface ScoreProfile {
  user_id: string;
  user_name?: string;
  github_pr_score?: number;
  jira_issue_score?: number;
  pr_info?: PrScoreInfo[];
  issue_links?: string[];
  readonly total_score: number;
}
