/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

/**
 * Individual search result.
 */
export interface SearchResult {
  source: string;
  id: string;
  title: string;
  url?: string | null;
  author?: string | null;
  context: string;
  created_at?: string | null;
}
