/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */
import type { SyncAllResponseGithub } from './syncAllResponseGithub';
import type { SyncAllResponseJira } from './syncAllResponseJira';

/**
 * Response schema for sync all operation.
 */
export interface SyncAllResponse {
  status: string;
  github?: SyncAllResponseGithub;
  jira?: SyncAllResponseJira;
  total_embeddings: number;
  errors?: string[];
}
