/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request schema for syncing all vectors from GitHub and Jira.
 */
export interface SyncAllRequest {
  /** Sync GitHub PRs */
  sync_github?: boolean;
  /** Sync Jira issues */
  sync_jira?: boolean;
  /**
   * Max PRs to fetch per GitHub author
   * @minimum 1
   * @maximum 500
   */
  github_max_prs_per_author?: number;
  /** Specific Jira projects to sync (None = all) */
  jira_project_keys?: string[] | null;
  /**
   * Max Jira issues to fetch per project
   * @minimum 1
   * @maximum 1000
   */
  jira_max_issues?: number;
  /** Include closed/done Jira issues */
  jira_include_closed?: boolean;
  /** Sync Jira issue comments */
  jira_sync_comments?: boolean;
}
