/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

export interface TeamMembersCard {
  total: number;
  new_this_month: number;
  developers: number;
  admins: number;
}
