/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

/**
 * Access token schema.
 */
export interface Token {
  access_token: string;
  token_type?: string;
}
