/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request schema for unified search across all sources.
 */
export interface UnifiedSearchRequest {
  /** Search query text */
  query: string;
  /**
   * Max results to return
   * @minimum 1
   * @maximum 100
   */
  n_results?: number;
  /** Search GitHub PRs */
  search_github?: boolean;
  /** Search Jira issues */
  search_jira?: boolean;
  /** Filter GitHub results by author */
  github_author_login?: string | null;
  /** Filter Jira results by project */
  jira_project_key?: string | null;
  /** Filter Jira results by assignee */
  jira_assignee_id?: string | null;
}
