/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */
import type { SearchResult } from './searchResult';

/**
 * Response schema for unified search.
 */
export interface UnifiedSearchResponse {
  query: string;
  total_results: number;
  github_results: number;
  jira_results: number;
  results: SearchResult[];
}
