/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request to update skills/domains.
 */
export interface UpdateSkillsRequest {
  skills?: string[] | null;
  domains?: string[] | null;
}
