/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

/**
 * User self-update schema.
 */
export interface UserUpdateMe {
  full_name?: string | null;
  email?: string | null;
}
