/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */
import type { UserPublic } from './userPublic';

/**
 * Multiple users public schema.
 */
export interface UsersPublic {
  data: UserPublic[];
  count: number;
}
