/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */
import type { Role } from './role';

/**
 * User update schema.
 */
export interface UserUpdate {
  email?: string | null;
  password?: string | null;
  is_active?: boolean | null;
  is_superuser?: boolean | null;
  full_name?: string | null;
  role?: Role | null;
}
