/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

export interface UserWorkload {
  user_id: string;
  name: string;
  jira_workload: number;
  github_workload: number;
  total_workload: number;
}
