/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */
import type { Role } from './role';

/**
 * User creation schema.
 */
export interface UserCreate {
  /** @maxLength 255 */
  email: string;
  /**
   * @minLength 8
   * @maxLength 128
   */
  password: string;
  is_active?: boolean;
  is_superuser?: boolean;
  full_name?: string | null;
  role?: Role;
}
