/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
}
