/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * FastAPI Backend Project
 * OpenAPI spec version: 0.1.0
 */

export type VectorEmbeddingsSearchSimilarPrsParams = {
query: string;
n_results?: number;
author_login?: string | null;
};
